<a href="https://colab.research.google.com/github/Christopher-Ramirez-S/An-lisis-de-datos/blob/Rafa/tarea_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#laboratorio individual Rafael Garcia

import pandas as pd

students = students = [('Ana', 23, 'San Jose', 'A'),
            ('Esteban', 22, 'Heredia', 'B'),
            ('Juan', 22, 'Cartago', 'A'),
            ('Karla', 22, 'Limón', 'A'),
            ('Ernesto', 21, 'Heredia', 'B'),
            ('Lucia', 24, 'Alajuela', 'A'),
            ('Pedro', 23, 'Puntarenas', 'C'),
            ('Maria', 22, 'Guanacaste', 'B'),
            ('Andres', 21, 'San Jose', 'C'),
            ('Laura', 23, 'Cartago', 'A'),
            ('Diego', 24, 'Heredia', 'B'),
            ('Sofia', 22, 'Limón', 'C'),
            ('Javier', 25, 'San Jose', 'B'),
            ('Gabriela', 23, 'Alajuela', 'A'),
            ('Felipe', 21, 'Cartago', 'C'),
            ('Daniela', 22, 'Guanacaste', 'B'),
            ('Adrian', 24, 'Limón', 'A'),
            ('Carmen', 23, 'Puntarenas', 'B'),
            ('Luis', 22, 'Heredia', 'C'),
            ('Natalia', 24, 'San Jose', 'A'),
            ('Ricardo', 21, 'Cartago', 'B'),
            ('Valeria', 22, 'Alajuela', 'C'),
            ('Miguel', 23, 'Limón', 'A'),
            ('Fernanda', 22, 'Heredia', 'B'),
            ('Jose', 21, 'Guanacaste', 'C'),
            ('Manuel', 23, 'San Jose', 'B'),
            ('Elena', 24, 'Puntarenas', 'A'),
            ('Marcos', 22, 'Cartago', 'B'),
            ('Rosa', 23, 'Guanacaste', 'C'),
            ('Isabel', 21, 'Heredia', 'A')]






df = pd.DataFrame(students, columns =['Nombre', 'Edad', 'Ciudad', 'Seccion'])
df

      Nombre  Edad      Ciudad Seccion
0        Ana    23    San Jose       A
1    Esteban    22     Heredia       B
2       Juan    22     Cartago       A
3      Karla    22       Limón       A
4    Ernesto    21     Heredia       B
5      Lucia    24    Alajuela       A
6      Pedro    23  Puntarenas       C
7      Maria    22  Guanacaste       B
8     Andres    21    San Jose       C
9      Laura    23     Cartago       A
10     Diego    24     Heredia       B
11     Sofia    22       Limón       C
12    Javier    25    San Jose       B
13  Gabriela    23    Alajuela       A
14    Felipe    21     Cartago       C
15   Daniela    22  Guanacaste       B
16    Adrian    24       Limón       A
17    Carmen    23  Puntarenas       B
18      Luis    22     Heredia       C
19   Natalia    24    San Jose       A
20   Ricardo    21     Cartago       B
21   Valeria    22    Alajuela       C
22    Miguel    23       Limón       A
23  Fernanda    22     Heredia       B
24      Jose    21  Guanacaste       C
25    Manuel    23    San Jose       B
26     Elena    24  Puntarenas       A
27    Marcos    22     Cartago       B
28      Rosa    23  Guanacaste       C
29    Isabel    21     Heredia       A

In [ ]:
def getIndexes(dfObj, value):

    listOfPos = []
    result = dfObj.isin([value])
    seriesObj = result.any()
    columnNames = list(seriesObj[seriesObj == True].index)

    for col in columnNames:
        rows = list(result[col][result[col] == True].index)

        for row in rows:
            listOfPos.append((row, col))

    return listOfPos

listOfPositions = getIndexes(df, 'Heredia')

print('Index positions of 22 in Dataframe : ')

for i in range(len(listOfPositions)):
    print( listOfPositions[i])

Index positions of 22 in Dataframe :
(1, 'Ciudad')
(4, 'Ciudad')
(10, 'Ciudad')